services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "5001:5001"
    depends_on:
      - user-service
      - product-service
      - order-service
      - admin-service
    environment:
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
      - ADMIN_SERVICE_URL=http://admin-service:4000

  user-service:
    build: ./user-details
    container_name: user-service
    ports:
      - "3001:3001"

  product-service:
    build: ./product-details
    container_name: product-service
    ports:
      - "3002:3002"

  order-service:
    build: ./order-details
    container_name: order-service
    ports:
      - "3003:3003"

  admin-service:
    build: ./admin
    container_name: admin-service
    ports:
      - "4000:4000"
